# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Cafe',
        ),
        migrations.RemoveField(
            model_name='sellerfeedback',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='dish',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Cafe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Cafe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SellerFeedback',
        ),
        migrations.AddField(
            model_name='cafefeedback',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Cafe'),
        ),
        migrations.AddField(
            model_name='cafefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
