# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170521_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
