# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_orderdish_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='feedback',
            new_name='comment',
        ),
    ]
